ingress:
  enabled: true
  hostname: blog.192.168.2.204.xip.bingnet.cloud
  ingressClassName: nginx
  tls: true
mariadb:
  auth:
    password: nopasswd
    rootPassword: nopasswd
service:
  type: ClusterIP
wordpressUsername: admin
wordpressPassword: nopasswd
